services:
  minuso_joaquin_mqtt_async:
    build: .
    container_name: minuso_joaquin_mqtt_container
    environment:
      - SERVIDOR=broker.hivemq.com
      - TOPICO_SUB_1=ingenieria/datos/1
      - TOPICO_SUB_2=ingenieria/datos/2
      - TOPICO_PUB=ingenieria/minuso/estado
    restart: always